remote_theme:  volny / creative-theme-jekyll
# Site settings
title: Bella Noche Pijamas
email: bellanochepijamas@gmail.com
instagram_username: bellanochepijamas
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

collections:
  -mujeres:
    main_image: /img/mainmujeres.jpg
    main_page: /mujeres.html
    name: Mujeres
    output: true
    permalink: /mujeres/:name
  -hombres:
    main_image: /img/mainhombres.jpg
    main_page: /hombres.html
    name: Hombres
    output: true
    permalink: /hombres/:name
  -ninos:
    main_image: /img/mainninos.jpg
    main_page: /ninos.html
    name: Ni√±os
    output: true
    permalink: /ninos/:name
  -ropadecama:
    main_image: /img/mainropacama.jpg
    main_page: /ropacama.html
    name: Ropa de Cama
    output: true
    permalink: /ropacama/:name

collections_dir: collections
