remote_theme:  volny / creative-theme-jekyll
# Site settings
title: Bella Noche Pijamas
email: bellanochepijamas@gmail.com

description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


whatsapp_link:
whatsapp: BellaNoche
whatsapp_link: https://wa.me/573103076859
instagram_username: bellanochepijamas
# Build settings
markdown: kramdown

collections:
  -mujeres:
    main_image: /img/portfolio/mainmujeres.png
    main_page: /mujeres/
    name: Mujeres
    output: true
    permalink: /mujeres/:name
  -hombres:
    main_image: /img/portfolio/mainhombres.jpeg
    main_page: /hombres/
    name: Hombres
    output: true
    permalink: /hombres/:name
  -ninos:
    main_image: /img/portfolio/mainninos.jpeg
    main_page: /ninos/
    name: Ni√±os
    output: true
    permalink: /ninos/:name
  -ropadecama:
    main_image: /img/portfolio/mainropacama.jpeg
    main_page: /ropacama/
    name: Ropa de Cama
    output: true
    permalink: /ropacama/:name

collections_dir: collections
