remote_theme: volny / creative-theme-jekyll
# Site settings
title: Bella Noche Pijamas
email: bellanochepijamas@gmail.com

description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


whatsapp_link:
whatsapp: Chatea conmigo
whatsapp_link: https://wa.me/573103076859
instagram_username: bellanochepijamas
# Build settings
markdown: kramdown

collections:
  -1mujeres:
    output: true
    main_image: /img/portfolio/mainmujeres.png
    main_page: /mujeres/
    name: Mujeres
    permalink: /mujeres/:name
  -2hombres:
    output: true
    main_image: /img/portfolio/mainhombres.jpeg
    main_page: /hombres/
    name: Hombres
    permalink: /hombres/:name
  -3ninos:
    output: true
    main_image: /img/portfolio/mainninos.jpeg
    main_page: /ninos/
    name: Kids
    permalink: /ninos/:name
  -4ropadecama:
    output: true
    main_image: /img/portfolio/mainropacama.jpeg
    main_page: /ropacama/
    name: Ropa de Cama
    permalink: /ropacama/:name
